apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/psuryasanthoshkumar9/Terraform.git
    targetRevision: main
    path: google-store-DevOps-project-New/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: google
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
