apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding # Binds role to an identity.
metadata:
  name: fluent-bit
roleRef:
  kind: ClusterRole
  name: fluent-bit
  apiGroup: rbac.authorization.k8s.io # References the ClusterRole created above.
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: kube-logging