apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: kube-logging
spec:
  serviceName: elasticsearch # Links StatefulSet to headless service , Enables stable DNS.
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch # Labels used by: StatefulSet, Service, DNS
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0 # Elasticsearch version, Must match Kibana version.
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 9200
          name: rest # REST API (used by Kibana, Fluent Bit).
        - containerPort: 9300
          name: inter-node  # Internal Elasticsearch cluster communication.
        volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data # Where Elasticsearch stores indices.
        env:
          - name: cluster.name
            value: k8s-logs # Logical cluster name.
          - name: node.name
            valueFrom: 
              fieldRef:
                fieldPath: metadata.name # Each pod uses its own name (es-cluster-0).
          - name: discovery.seed_hosts # List of all Elasticsearch pods, Required for node discovery.
            value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
          - name: cluster.initial_master_nodes # Prevents split-brain during first startup.
            value: "es-cluster-0,es-cluster-1,es-cluster-2"
          - name: ES_JAVA_OPTS 
            value: "-Xms512m -Xmx512m" # JVM heap settings.
      initContainers: #  Run before Elasticsearch starts.
      - name: fix-permission # Fixes file ownership for mounted volume.
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ebs-storage
      resources:
        requests:
          storage: 10Gi
